service: serverless-fastapi-dynamodb
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: ap-southeast-1
functions:
  api:
    handler: main.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements